basePath: /
definitions:
  handlers.Response:
    properties:
      message:
        type: string
      results: {}
      success:
        type: boolean
    type: object
  models.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.RegisterInput:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - password
    type: object
  models.UpdateInput:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
      picture:
        type: string
      role_id:
        type: integer
    type: object
host: localhost:8888
info:
  contact: {}
  description: belajar swagger.
  title: backend app
  version: 1.0.0
paths:
  /deleteuser/{id}:
    delete:
      description: Delete user by UUID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Delete user
      tags:
      - users
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Login user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create new user account
      parameters:
      - description: Register Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Register new user
      tags:
      - users
  /updateuser/{id}:
    patch:
      consumes:
      - application/json
      description: Update user by UUID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Update user
      tags:
      - users
  /users:
    get:
      description: Get list of users from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Get all users
      tags:
      - users
  /users/{id}:
    get:
      description: Get single user by UUID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
